

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JooleProject_DAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class JooleDatabaseEntities : DbContext
{
    public JooleDatabaseEntities()
        : base("name=JooleDatabaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Category> Category { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<Property> Property { get; set; }

    public virtual DbSet<PropertyValue> PropertyValue { get; set; }

    public virtual DbSet<SubCategory> SubCategory { get; set; }

    public virtual DbSet<TechSpecFilter> TechSpecFilter { get; set; }

    public virtual DbSet<TypeFilter> TypeFilter { get; set; }

    public virtual DbSet<User> User { get; set; }

}

}

